<a href="https://colab.research.google.com/github/israakadhem0-coder/Drug-discovery_ML/blob/main/python/CDD_ML_Part_1_bioactivity_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.3)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 883.0 kB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 3.3 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.5 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.3 url-normalize-3.0.0

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for NRF2**

In [3]:
# Target search for NRF2
target = new_client.target
target_query = target.search('NRF2')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Keap1/Nrf2,17.0,False,CHEMBL3038498,"[{'accession': 'Q16236', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
1,[],Rattus norvegicus,KEAP1/NRF2,17.0,False,CHEMBL4296095,"[{'accession': 'O54968', 'component_descriptio...",PROTEIN COMPLEX,10116
2,[],Homo sapiens,NRF2-MAFG,17.0,False,CHEMBL5483087,"[{'accession': 'Q16236', 'component_descriptio...",PROTEIN COMPLEX,9606
3,[],Mus musculus,Nuclear factor erythroid 2-related factor 2,15.0,False,CHEMBL1075148,"[{'accession': 'Q60795', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Homo sapiens,Nuclear factor erythroid 2-related factor 2,15.0,False,CHEMBL1075094,"[{'accession': 'Q16236', 'component_descriptio...",SINGLE PROTEIN,9606
5,[],Mus musculus,Kelch-like ECH-associated protein 1/Nuclear fa...,15.0,False,CHEMBL4296107,"[{'accession': 'Q60795', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
6,[],Rattus norvegicus,Nuclear factor erythroid 2-related factor 2,14.0,False,CHEMBL1075141,"[{'accession': 'O54968', 'component_descriptio...",SINGLE PROTEIN,10116
7,[],Rattus norvegicus,Kelch-like ECH-associated protein 1,13.0,False,CHEMBL4523596,"[{'accession': 'P57790', 'component_descriptio...",SINGLE PROTEIN,10116
8,[],Mus musculus,Kelch-like ECH-associated protein 1,12.0,False,CHEMBL3562164,"[{'accession': 'Q9Z2X8', 'component_descriptio...",SINGLE PROTEIN,10090
9,[],Homo sapiens,Kelch-like ECH-associated protein 1,11.0,False,CHEMBL2069156,"[{'accession': 'Q14145', 'component_descriptio...",SINGLE PROTEIN,9606
10,[],Mus musculus,Protein cereblon/Kelch-like ECH-associated pro...,11.0,False,CHEMBL5465249,"[{'accession': 'Q9Z2X8', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,10090
11,[],Homo sapiens,Kelch-like ECH-associated protein 1/Bromodomai...,10.0,False,CHEMBL6193832,"[{'accession': 'O60885', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
12,[],Homo sapiens,Kelch-like ECH-associated protein 1/Microtubul...,9.0,False,CHEMBL4296122,"[{'accession': 'P10636', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
13,[],Homo sapiens,Kelch-like ECH-associated protein 1/Microtubul...,8.0,False,CHEMBL4296123,"[{'accession': 'P10636', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
14,[],Homo sapiens,Sequestosome-1/Kelch-like ECH-associated prote...,7.0,False,CHEMBL4106129,"[{'accession': 'Q14145', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
15,[],Homo sapiens,Kelch-like ECH-associated protein 1/Cyclin-dep...,7.0,False,CHEMBL6193838,"[{'accession': 'P50750', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

### **Select and retrieve bioactivity data for NRF2**

In [17]:
selected_target = targets.target_chembl_id[4]
selected_target

'CHEMBL1075094'

In [18]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [19]:
df = pd.DataFrame.from_dict(res)

In [20]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,19259356,[],CHEMBL4403711,Inhibition of Nrf2 (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,uM,UO_0000065,None,5.39
1,None,None,19259357,[],CHEMBL4403711,Inhibition of Nrf2 (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,nM,UO_0000065,None,115.0
2,None,None,19453585,[],CHEMBL4434437,Inhibition of NRF2 in human MDA-MB-231 cells h...,B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,nM,UO_0000065,None,29.19

In [21]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [22]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [23]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [24]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/TAHA"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/TAHA’: File exists

In [25]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/TAHA"

In [26]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/TAHA"

total 6
-rw------- 1 root root 5247 Aug 25 18:22 bioactivity_data.csv

Let's see the CSV files that we have so far.

In [27]:
! ls

bioactivity_data.csv  gdrive  sample_data

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [28]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,19259356,[],CHEMBL4403711,Inhibition of Nrf2 (unknown origin),B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@H](C(=O)NCC(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](Cc1ccccc1)C(=O)O)[C@@H](C)O,,,CHEMBL4402544,Eur J Med Chem,2020,"{'bei': '6.07', 'le': '0.12', 'lle': '9.46', 'sei': '1.28'}",,CHEMBL3617787,,CHEMBL3617787,5.27,0,http://www.openphacts.org/units/Nanomolar,3215694,=,1,1,=,,IC50,nM,,5390.0,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,uM,UO_0000065,,5.39
,,19259357,[],CHEMBL4403711,Inhibition of Nrf2 (unknown origin),B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@H](C(=O)NCC(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC(C)C)C(=O)O)[C@@H](C)O,,,CHEMBL4402544,Eur J Med Chem,2020,"{'bei': '8.65', 'le': '0.17', 'lle': '10.69', 'sei': '1.90'}",,CHEMBL3928693,,CHEMBL3928693,6.94,0,http://www.openphacts.org/units/Nanomolar,3215695,=,1,1,=,,IC50,nM,,115.0,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,nM,UO_0000065,,115.0
,,19453585,[],CHEMBL4434437,Inhibition of NRF2 in human MDA-MB-231 cells harboring ARE-GFP-Luc assessed as reduction in ARE-luciferase activity after 16 hrs by firefly luciferase reporter gene assay,B,,,BAO_0000190,BAO_0000219,cell-based format,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[C@@]1(C)CC(=O)C(O)=C(C)[C@@H]1C[C@H]3OC(=O)[C@H](OC(=O)C=C(C)C)[C@@H]24,,,CHEMBL4433256,Bioorg Med Chem Lett,2019,"{'bei': '14.48', 'le': '0.28', 'lle': '7.01', 'sei': '4.54'}",,CHEMBL459546,,CHEMBL459546,7.54,0,http://www.openphacts.org/units/Nanomolar,3250423,=,1,1,=,,IC50,nM,,29.19,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,nM,UO_0000065,,29.19
"{'action_type': 'INHIBITOR', 'description': 'Negatively effects (inhibits) the normal functioning of the protein e.g., prevention of enzymatic reaction or activation of downstream pathway', 'parent_type': 'NEGATIVE MODULATOR'}",,26129625,[],CHEMBL5617281,Inhibition of NRF2 (unknown origin),B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cc(C)cc(Nc2nc(C)c(-c3ccccc3)cc2C#N)c1,,,CHEMBL5614432,Eur J Med Chem,2024,,,CHEMBL5288795,,CHEMBL5288795,,0,http://www.openphacts.org/units/Nanomolar,4125916,~,1,1,~,,IC50,nM,,5000.0,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,uM,UO_0000065,,5.0
"{'action_type': 'INHIBITOR', 'description': 'Negatively effects (inhibits) the normal functioning of the protein e.g., prevention of enzymatic reaction or activation of downstream pathway', 'parent_type': 'NEGATIVE MODULATOR'}",,26129626,[],CHEMBL5617281,Inhibition of NRF2 (unknown origin),B,,,BAO_0000190,BAO_0000357,single protein format,Nc1ccc(OCCC2CCCCC2)cc1,,,CHEMBL5614432,Eur J Med Chem,2024,"{'bei': '25.25', 'le': '0.47', 'lle': '1.92', 'sei': '15.71'}",,CHEMBL5619019,,CHEMBL5619019,5.54,0,http://www.openphacts.org/units/Nanomolar,4125917,=,1,1,=,,IC50,nM,,2900.0,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,uM,UO_0000065,,2.9
"{'action_type': 'INHIBITOR', 'description': 'Negatively effects (inhibits) the normal functioning of the protein e.g., prevention of enzymatic reaction or activation of downstream pathway', 'parent_type': 'NEGATIVE MODULATOR'}",,26129639,[],CHEMBL5617293,Inhibition of NRF2 in human KYSE-70 cells,B,,,BAO_0000190,BAO_0000219,cell-based format,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,,,CHEMBL5614432,Eur J Med Chem,2024,"{'bei': '18.45', 'le': '0.44', 'lle': '5.77', 'sei': '9.09'}",,CHEMBL1197091,HALOFUGINONE,CHEMBL1197091,7.65,0,http://www.openphacts.org/units/Nanomolar,4125925,=,1,1,=,,IC50,nM,,22.3,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,nM,UO_0000065,,22.3
"{'action_type': 'INHIBITOR', 'description': 'Negatively effects (inhibits) the normal functioning of the protein e.g., prevention of enzymatic reaction or activation of downstream pathway', 'parent_type': 'NEGATIVE MODULATOR'}",,26129640,[],CHEMBL5617294,Inhibition of NRF2 in human A549 cells,B,,,BAO_0000190,BAO_0000219,cell-based format,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,,,CHEMBL5614432,Eur J Med Chem,2024,"{'bei': '17.92', 'le': '0.42', 'lle': '5.55', 'sei': '8.82'}",,CHEMBL1197091,HALOFUGINONE,CHEMBL1197091,7.43,0,http://www.openphacts.org/units/Nanomolar,4125925,=,1,1,=,,IC50,nM,,37.2,CHEMBL1075094,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,,,IC50,nM,UO_0000065,,37.2

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [29]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,19259356,[],CHEMBL4403711,Inhibition of Nrf2 (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,uM,UO_0000065,None,5.39
1,None,None,19259357,[],CHEMBL4403711,Inhibition of Nrf2 (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,nM,UO_0000065,None,115.0
2,None,None,19453585,[],CHEMBL4434437,Inhibition of NRF2 in human MDA-MB-231 cells h...,B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,nM,UO_0000065,None,29.19
3,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129625,[],CHEMBL5617281,Inhibition of NRF2 (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,uM,UO_0000065,None,5.0
4,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129626,[],CHEMBL5617281,Inhibition of NRF2 (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,uM,UO_0000065,None,2.9
5,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129639,[],CHEMBL5617293,Inhibition of NRF2 in human KYSE-70 cells,B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,nM,UO_0000065,None,22.3
6,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129640,[],CHEMBL5617294,Inhibition of NRF2 in human A549 cells,B,None,None,BAO_0000190,...,Homo sapiens,Nuclear factor erythroid 2-related factor 2,9606,None,None,IC50,nM,UO_0000065,None,37.2

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [30]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [31]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [32]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [33]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [34]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [35]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL3617787,CC(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(...,intermediate,5390.0
1,CHEMBL3928693,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[C...,active,115.0
2,CHEMBL459546,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,active,29.19
3,CHEMBL5288795,Cc1cc(C)cc(Nc2nc(C)c(-c3ccccc3)cc2C#N)c1,intermediate,5000.0
4,CHEMBL5619019,Nc1ccc(OCCC2CCCCC2)cc1,intermediate,2900.0
5,CHEMBL1197091,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,active,22.3
6,CHEMBL1197091,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,active,37.2

### **Alternative method**

In [36]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL3617787,CC(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(...,5390.0
1,CHEMBL3928693,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[C...,115.0
2,CHEMBL459546,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,29.19
3,CHEMBL5288795,Cc1cc(C)cc(Nc2nc(C)c(-c3ccccc3)cc2C#N)c1,5000.0
4,CHEMBL5619019,Nc1ccc(OCCC2CCCCC2)cc1,2900.0
5,CHEMBL1197091,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,22.3
6,CHEMBL1197091,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,37.2

In [37]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL3617787,CC(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](CCC(=O)O)C(...,5390.0,intermediate
1,CHEMBL3928693,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[C...,115.0,active
2,CHEMBL459546,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,29.19,active
3,CHEMBL5288795,Cc1cc(C)cc(Nc2nc(C)c(-c3ccccc3)cc2C#N)c1,5000.0,intermediate
4,CHEMBL5619019,Nc1ccc(OCCC2CCCCC2)cc1,2900.0,intermediate
5,CHEMBL1197091,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,22.3,active
6,CHEMBL1197091,O=C(CC1NCCCC1O)Cn1cnc2cc(Br)c(Cl)cc2c1=O,37.2,active

Saves dataframe to CSV file

In [38]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [39]:
! ls -l

total 20
-rw-r--r-- 1 root root 5247 Aug 25 18:22 bioactivity_data.csv
-rw-r--r-- 1 root root  743 Aug 25 18:23 bioactivity_preprocessed_data.csv
drwx------ 5 root root 4096 Aug 25 18:22 gdrive
drwxr-xr-x 1 root root 4096 Aug 24 13:21 sample_data

Let's copy to the Google Drive

In [40]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/TAHA"

In [41]:
! ls "/content/gdrive/My Drive/Colab Notebooks/TAHA"

bioactivity_data.csv  bioactivity_preprocessed_data.csv

---