# **Bioinformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

## **Download PaDEL-Descriptor**

In [1]:
!pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.17-py3-none-any.whl.metadata (6.5 kB)
Downloading padelpy-0.1.17-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 50.6 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.17

In [16]:
from padelpy import padeldescriptor

padeldescriptor(
    mol_dir='molecule.smi',
    d_file='descriptors_output.csv',
    fingerprints=True,
    removesalt=True
)

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [4]:
import pandas as pd

In [5]:
df3 = pd.read_csv('bioactivity_data_2class.csv')

In [6]:
df3

,molecule_chembl_id,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors,pIC50,bioactivity_class
0,CHEMBL2402206,Cc1ccc(S(=O)(=O)c2cnc(SCC(=O)Nc3ccccc3C(F)(F)F...,497.520,3.96914,2.0,6.0,3.928118,inactive
1,CHEMBL2402205,CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](...,1858.036,-4.81120,24.0,24.0,7.481486,active
2,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,614.654,3.41680,2.0,8.0,7.698970,active
3,CHEMBL3632707,CCOC(=O)CN(c1ccc(N(CC(=O)OCC)S(=O)(=O)c2ccc(OC...,670.762,4.37380,0.0,10.0,3.602060,inactive
4,CHEMBL3632711,COc1ccc(S(=O)(=O)N(CC(N)=O)c2ccc(N(CC(N)=O)S(=...,612.686,2.21820,2.0,8.0,7.356547,active
...,...,...,...,...,...,...,...,...
259,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,614.654,3.41680,2.0,8.0,7.619789,active
260,CHEMBL3237245,COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=...,614.654,3.41680,2.0,8.0,8.113509,active
261,CHEMBL5272223,CC(=O)N[C@@H](CC(=O)O)C(=O)N1CSC[C@H]1C(=O)N[C...,859.909,-2.91190,11.0,13.0,7.508638,active
262,CHEMBL1232461,CCNC(=O)C[C@@H]1N=C(c2ccc(Cl)cc2)c2cc(OC)ccc2-...,423.904,3.65602,1.0,5.0,5.000000,inactive
263,CHEMBL6102564,NC(=O)CN(c1ccc(N(CC(N)=O)S(=O)(=O)c2ccc(N)cc2)...,567.649,1.78320,3.0,7.0,6.638272,active

In [7]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [8]:
! cat molecule.smi | head -5

Cc1ccc(S(=O)(=O)c2cnc(SCC(=O)Nc3ccccc3C(F)(F)F)[nH]c2=O)c(C)c1	CHEMBL2402206
CC(C)C[C@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](CCC(=O)O)NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](C)NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](C)N)[C@@H](C)O)C(=O)O	CHEMBL2402205
COc1ccc(S(=O)(=O)N(CC(=O)O)c2ccc(N(CC(=O)O)S(=O)(=O)c3ccc(OC)cc3)c3ccccc23)cc1	CHEMBL3237245
CCOC(=O)CN(c1ccc(N(CC(=O)OCC)S(=O)(=O)c2ccc(OC)cc2)c2ccccc12)S(=O)(=O)c1ccc(OC)cc1	CHEMBL3632707
COc1ccc(S(=O)(=O)N(CC(N)=O)c2ccc(N(CC(N)=O)S(=O)(=O)c3ccc(OC)cc3)c3ccccc23)cc1	CHEMBL3632711

In [9]:
! cat molecule.smi | wc -l

264

## **Calculate fingerprint descriptors**

In [10]:
%%writefile padel.sh
java -Xms512m -Xmx512m -jar PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -retained3d-descriptors -file descriptors_output.csv -dir ./ -fingerprints

Writing padel.sh

### **Calculate PaDEL descriptors**

In [11]:
! cat padel.sh

java -Xms512m -Xmx512m -jar PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -retained3d-descriptors -file descriptors_output.csv -dir ./ -fingerprints

In [12]:
! bash padel.sh

Error: Unable to access jarfile PaDEL-Descriptor/PaDEL-Descriptor.jar

In [13]:
! ls -l

total 108
-rw-r--r-- 1 root root 53072 Sep  2 19:44 bioactivity_data_2class.csv
-rw-r--r-- 1 root root 11348 Sep  2 19:43 descriptors_output.csv
-rw-r--r-- 1 root root 34808 Sep  2 19:44 molecule.smi
-rw-r--r-- 1 root root   153 Sep  2 19:44 padel.sh
drwxr-xr-x 1 root root  4096 Aug 24 13:21 sample_data

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [14]:
df3_X = pd.read_csv('descriptors_output.csv')

In [15]:
df3_X

Empty DataFrame
Columns: [Name, PubchemFP0, PubchemFP1, PubchemFP2, PubchemFP3, PubchemFP4, PubchemFP5, PubchemFP6, PubchemFP7, PubchemFP8, PubchemFP9, PubchemFP10, PubchemFP11, PubchemFP12, PubchemFP13, PubchemFP14, PubchemFP15, PubchemFP16, PubchemFP17, PubchemFP18, PubchemFP19, PubchemFP20, PubchemFP21, PubchemFP22, PubchemFP23, PubchemFP24, PubchemFP25, PubchemFP26, PubchemFP27, PubchemFP28, PubchemFP29, PubchemFP30, PubchemFP31, PubchemFP32, PubchemFP33, PubchemFP34, PubchemFP35, PubchemFP36, PubchemFP37, PubchemFP38, PubchemFP39, PubchemFP40, PubchemFP41, PubchemFP42, PubchemFP43, PubchemFP44, PubchemFP45, PubchemFP46, PubchemFP47, PubchemFP48, PubchemFP49, PubchemFP50, PubchemFP51, PubchemFP52, PubchemFP53, PubchemFP54, PubchemFP55, PubchemFP56, PubchemFP57, PubchemFP58, PubchemFP59, PubchemFP60, PubchemFP61, PubchemFP62, PubchemFP63, PubchemFP64, PubchemFP65, PubchemFP66, PubchemFP67, PubchemFP68, PubchemFP69, PubchemFP70, PubchemFP71, PubchemFP72, PubchemFP73, PubchemFP74, PubchemFP75, PubchemFP76, PubchemFP77, PubchemFP78, PubchemFP79, PubchemFP80, PubchemFP81, PubchemFP82, PubchemFP83, PubchemFP84, PubchemFP85, PubchemFP86, PubchemFP87, PubchemFP88, PubchemFP89, PubchemFP90, PubchemFP91, PubchemFP92, PubchemFP93, PubchemFP94, PubchemFP95, PubchemFP96, PubchemFP97, PubchemFP98, ...]
Index: []

[0 rows x 882 columns]

In [17]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

Empty DataFrame
Columns: [PubchemFP0, PubchemFP1, PubchemFP2, PubchemFP3, PubchemFP4, PubchemFP5, PubchemFP6, PubchemFP7, PubchemFP8, PubchemFP9, PubchemFP10, PubchemFP11, PubchemFP12, PubchemFP13, PubchemFP14, PubchemFP15, PubchemFP16, PubchemFP17, PubchemFP18, PubchemFP19, PubchemFP20, PubchemFP21, PubchemFP22, PubchemFP23, PubchemFP24, PubchemFP25, PubchemFP26, PubchemFP27, PubchemFP28, PubchemFP29, PubchemFP30, PubchemFP31, PubchemFP32, PubchemFP33, PubchemFP34, PubchemFP35, PubchemFP36, PubchemFP37, PubchemFP38, PubchemFP39, PubchemFP40, PubchemFP41, PubchemFP42, PubchemFP43, PubchemFP44, PubchemFP45, PubchemFP46, PubchemFP47, PubchemFP48, PubchemFP49, PubchemFP50, PubchemFP51, PubchemFP52, PubchemFP53, PubchemFP54, PubchemFP55, PubchemFP56, PubchemFP57, PubchemFP58, PubchemFP59, PubchemFP60, PubchemFP61, PubchemFP62, PubchemFP63, PubchemFP64, PubchemFP65, PubchemFP66, PubchemFP67, PubchemFP68, PubchemFP69, PubchemFP70, PubchemFP71, PubchemFP72, PubchemFP73, PubchemFP74, PubchemFP75, PubchemFP76, PubchemFP77, PubchemFP78, PubchemFP79, PubchemFP80, PubchemFP81, PubchemFP82, PubchemFP83, PubchemFP84, PubchemFP85, PubchemFP86, PubchemFP87, PubchemFP88, PubchemFP89, PubchemFP90, PubchemFP91, PubchemFP92, PubchemFP93, PubchemFP94, PubchemFP95, PubchemFP96, PubchemFP97, PubchemFP98, PubchemFP99, ...]
Index: []

[0 rows x 881 columns]

## **Y variable**

### **Convert IC50 to pIC50**

In [18]:
df3_Y = df3['pIC50']
df3_Y

0      3.928118
1      7.481486
2      7.698970
3      3.602060
4      7.356547
         ...
259    7.619789
260    8.113509
261    7.508638
262    5.000000
263    6.638272
Name: pIC50, Length: 264, dtype: float64

## **Combining X and Y variable**

In [19]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.928118
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.481486
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.698970
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.602060
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.356547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.619789
260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.113509
261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.508638
262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.638272

In [20]:
dataset3.to_csv('NRF2_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**